### ISSUE TITLE
Inconsistencies in Consuming REST guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-rest-client-java#23]
- Should work with whole classes instead of code snippets

- Instruction asking users to create new classes is inconsistent with the other guides (and within the guide itself too)?

- Some code blocks are copyable when they shouldn't or don't need to be copyable

- Do we really need to link to the JSON Binding 1.0 User Guide twice?  And, do we need to mention the version?

- Command blocks should be copyable and be made consistent with the other guides

- Revise the names of the JUnit tests to be consistent and so we can easily tell which ones are for JSON-B and which is for JSON-P

**Comment by KyleAure** [comment]
@yeekangc I can start working on these changes.  Would you like me to create a new branch/PR or keep working off of the branch we have for the JSON-B changes?

**Comment by Kubik42** [comment]
@KyleAure That would work. You can create a branch directly in this repo if you have access (not sure). Sorry for merging your last PR too early, I wanted to see how things would look on the site before we published and it only picks up specific branches.

**Comment by yeekangc** [comment]
These should come after the JSON-B update is merged to after.

Thank you, @KyleAure.  Please coordinate with @Kubik42 and @evelinec.

**Comment by yeekangc** [comment]
Other considerations:

- Use `mvn compile` throughout: @Kubik42 mentioned that we should do this.  Noting it and Dmitry can elaborate on what it means.

- Mention under 'Starting the service' that the guide is setup to use loose application/config so users will have the service started from /start and making updates to code directly where the changes will be picked by the server dynamically.

**Comment by evelinec** [comment]
@KyleAure any updates on this issue? Thanks.

**Comment by KyleAure** [comment]
@evelinec Not yet been wrapping up the sessions guide.  I'll branch tomorrow and get started.  Thank you!

**Comment by KyleAure** [comment]
Tracking current to-do list
----
_Feel free to add on anything else you see!_
- [ ] Should work with whole classes instead of code snippets
- [ ] Instruction asking users to create new classes is inconsistent with the other guides (and within the guide itself too)?
- [ ] Some code blocks are copyable when they shouldn't or don't need to be copyable
- [ ] Do we really need to link to the JSON Binding 1.0 User Guide twice? And, do we need to mention the version?
- [ ] Command blocks should be copyable and be made consistent with the other guides
- [ ] Revise the names of the JUnit tests to be consistent and so we can easily tell which ones are for JSON-B and which is for JSON-P
- [ ] Use mvn compile throughout: Kubik42 mentioned that we should do this. Noting it and Dmitry can elaborate on what it means.
- [ ] Mention under 'Starting the service' that the guide is setup to use loose application/config so users will have the service started from /start and making updates to code directly where the changes will be picked by the server dynamically.

**Comment by evelinec** [comment]
Looks like this issue had been resolved.
